#!/usr/bin/env bash

if [[ "$BASH_VERSION" =~ ^3 ]]; then
    echo 'quinedb requires bash 4!'
    exit 1
fi

declare -A db

db=(
)

print_db(){
    echo "db=("
    i=0
    for k in "${!db[@]}"; do
        escaped_keys[$i]=$(printf %q "$k")
        i=$((i+1))
    done

    # sort the keys for deterministic printing
    IFS=$'\n' sorted=($(printf '%s' "${escaped_keys[*]}" | sort))
    unset IFS

    for k in "${sorted[@]}"; do
        unescaped=$(eval "echo $k")
        v=${db["$unescaped"]}
        echo "    [$k]=$(printf %q "$v")"
    done
    echo ")"
}

SEC1=$(cat <<'EOF'
#!/usr/bin/env bash

if [[ "$BASH_VERSION" =~ ^3 ]]; then
    echo 'quinedb requires bash 4!'
    exit 1
fi

declare -A db
EOF
)

SEC2=$(cat <<'EOF'
print_db(){
    echo "db=("
    i=0
    for k in "${!db[@]}"; do
        escaped_keys[$i]=$(printf %q "$k")
        i=$((i+1))
    done

    # sort the keys for deterministic printing
    IFS=$'\n' sorted=($(printf '%s' "${escaped_keys[*]}" | sort))
    unset IFS

    for k in "${sorted[@]}"; do
        unescaped=$(eval "echo $k")
        v=${db["$unescaped"]}
        echo "    [$k]=$(printf %q "$v")"
    done
    echo ")"
}
EOF
)

SEC3=$(cat <<'EOF'
print_self(){
    echo "$SEC1"; echo
    print_db; echo
    echo "$SEC2"; echo
    echo 'SEC1=$(cat <<'\'EOF\'
    echo "$SEC1"
    echo EOF
    echo \); echo
    echo 'SEC2=$(cat <<'\'EOF\'
    echo "$SEC2"
    echo EOF
    echo \); echo
    echo 'SEC3=$(cat <<'\'EOF\'
    echo "$SEC3"
    echo EOF
    echo \); echo
    echo "$SEC3"
}

case "$1" in
    "get")
        if [ "${db["$2"]+_}" ]; then
            v=${db["$2"]}
            echo "$(printf %q "$v")" >&2
        fi
    ;;
    "set")
        db["$2"]="$3"
        echo 'OK' >&2
    ;;
    "delete")
        unset 'db[$2]'
        echo 'OK' >&2
    ;;
    "keys")
        printf '%q\n' "${!db[@]}" >&2
    ;;
    *)
        echo "USAGE: quinedb [get k | set k v | delete k | keys]" >&2
    ;;
esac

print_self
EOF
)

print_self(){
    echo "$SEC1"; echo
    print_db; echo
    echo "$SEC2"; echo
    echo 'SEC1=$(cat <<'\'EOF\'
    echo "$SEC1"
    echo EOF
    echo \); echo
    echo 'SEC2=$(cat <<'\'EOF\'
    echo "$SEC2"
    echo EOF
    echo \); echo
    echo 'SEC3=$(cat <<'\'EOF\'
    echo "$SEC3"
    echo EOF
    echo \); echo
    echo "$SEC3"
}

case "$1" in
    "get")
        if [ "${db["$2"]+_}" ]; then
            v=${db["$2"]}
            echo "$(printf %q "$v")" >&2
        fi
    ;;
    "set")
        db["$2"]="$3"
        echo 'OK' >&2
    ;;
    "delete")
        unset 'db[$2]'
        echo 'OK' >&2
    ;;
    "keys")
        printf '%q\n' "${!db[@]}" >&2
    ;;
    *)
        echo "USAGE: quinedb [get k | set k v | delete k | keys]" >&2
    ;;
esac

print_self
